Don't use OkHttp internal APIs
These aren't stable from release to release. This particular method doesn't
exist in OkHttp 4 and causes a pretty nasty crash:

java.lang.IncompatibleClassChangeError: Expected static method okhttp3.internal.http.HttpMethod.permitsRequestBody(Ljava/lang/String;)Z
                     at com.trulioo.normalizedapi.ApiClient.buildRequest(ApiClient.java:1114)
                     at com.trulioo.normalizedapi.ApiClient.buildCall(ApiClient.java:1081)
                     at com.trulioo.normalizedapi.api.ConfigurationApi.getCountrySubdivisionsCall(ConfigurationApi.java:366)
                     at com.trulioo.normalizedapi.api.ConfigurationApi.getCountrySubdivisionsValidateBeforeCall(ConfigurationApi.java:378)
                     at com.trulioo.normalizedapi.api.ConfigurationApi.getCountrySubdivisionsWithHttpInfo(ConfigurationApi.java:407)
                     at com.trulioo.normalizedapi.api.ConfigurationApi.getCountrySubdivisions(ConfigurationApi.java:395)